# Generated by Django 5.2 on 2025-05-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylandingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='social_midia',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='tecnology',
        ),
    ]
