# Generated by Django 5.2 on 2025-05-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylandingpage', '0002_remove_sitesetup_social_midia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
